### ISSUE TITLE
When will the results and code for the CounterFact Dataset be released?

### ISSUE THREAD

**Issue by dong-river** [JasonForJoy/Model-Editing-Hurt#1]
Thank you for the great work. I wonder when will the results and code for the CounterFact Dataset be released.

**Comment by pkulium** [comment]
Similar question, when can find code for llama models?

Another question, when running with gpt2 model using python test-task.py, got error 
`RuntimeError: The size of tensor a (1024) must match the size of tensor b (1025) at non-singleton dimension 3`

**Comment by famoustourist** [comment]
Regarding the first question, you can download the LLaMA model into the hugging_cache folder, and then change the paths for the tokenizer, model, and parameters to the corresponding paths of the LLaMA model. @pkulium 

As for the second question, we tested it again and the problem you mentioned did not occur. Can you make your question more specific, or check if your experimental environment matches ours?

**Comment by pkulium** [comment]
Thanks for reply! @famoustourist 
For question one, I will follow your guidance.
For question two, I follow instruction to install conda env first then run with python test-task.py NER
`(EditHurt) [pkulium@amp-8 Model-Editing-Hurt]$ python test-task.py NER
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Traceback (most recent call last):
  File "/work/LAS/wzhang-lab/mingl/code/m_edit/Model-Editing-Hurt/./test-task-code/test-NER.py", line 121, in <module>
    pre_edit_outputs = model.generate(
  File "/work/LAS/wzhang-lab/mingl/.conda/envs/EditHurt/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/work/LAS/wzhang-lab/mingl/.conda/envs/EditHurt/lib/python3.9/site-packages/transformers/generation/utils.py", line 1522, in generate
    return self.greedy_search(
  File "/work/LAS/wzhang-lab/mingl/.conda/envs/EditHurt/lib/python3.9/site-packages/transformers/generation/utils.py", line 2339, in greedy_search
    outputs = self(
  File "/work/LAS/wzhang-lab/mingl/.conda/envs/EditHurt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/LAS/wzhang-lab/mingl/.conda/envs/EditHurt/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1080, in forward
    transformer_outputs = self.transformer(
  File "/work/LAS/wzhang-lab/mingl/.conda/envs/EditHurt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/LAS/wzhang-lab/mingl/.conda/envs/EditHurt/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 903, in forward
    outputs = block(
  File "/work/LAS/wzhang-lab/mingl/.conda/envs/EditHurt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/LAS/wzhang-lab/mingl/.conda/envs/EditHurt/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 391, in forward
    attn_outputs = self.attn(
  File "/work/LAS/wzhang-lab/mingl/.conda/envs/EditHurt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/LAS/wzhang-lab/mingl/.conda/envs/EditHurt/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 332, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/work/LAS/wzhang-lab/mingl/.conda/envs/EditHurt/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 203, in _attn
    attn_weights = torch.where(causal_mask, attn_weights.to(attn_weights.dtype), mask_value)
RuntimeError: The size of tensor a (1024) must match the size of tensor b (1025) at non-singleton dimension 3
Done`

**Comment by famoustourist** [comment]
@pkulium
We indeed did not encounter the issues you faced while running the program in our previous experiments. It might be possible that the model you are using is different from the one we used in our experiments. The model we adopted during the experimental process is GPT2-XL with the structure of GPT2LMHeadModel.

**Comment by Balloonn** [comment]
@pkulium @famoustourist 
I have encountered exactly same question when I run NER, OpenDomainQA, reasoning, summarization tasks on fine-tuned gpt2-xl model before editing. But I can run NLI, dialogue, ClosedDomainQA, SentimentAnalysis tasks on it. Have you resolved this problem?

**Comment by pkuliumiastate** [comment]
nope

> @pkulium @famoustourist I have encountered exactly same question when I run NER, OpenDomainQA, reasoning, summarization tasks on gpt2-xl model.
> 
> But I can run NLI, dialogue, ClosedDomainQA, SentimentAnalysis tasks on it.
> 
> The error occurs when the length of max_new_tokens is not 1 in function model.generate.
> 
> Have you solved this problem?

I haven't.

**Comment by Balloonn** [comment]
@pkulium 

I think the problem might be caused by the batch tokenizer when setting the padding="max_length".

I can run reasoning, OpenDomainQA, summarization after I set padding=True.

NER have further bugs, I changed per, org, loc to the same format as mis.

Hope this reply can help you.

**Comment by pkulium** [comment]
Is there any bash script to swap through to reproduce results in the paper?
